# -*- coding: utf-8 -*-
"""Copy of gpt2_sentiment_minimal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1INGdsGkARzjKu9mHeMQHfMSliOtYM5mT

# **Couple of Things to Note:**

1.
Some Protions of this colab page was taken directly from the "***NN_Deeper_NLPClassification.ipynb***" colab on UBlearns

2.
But the Code is mostly based on the original colab "***gpt2_sentiment_minimal.ipynb***"
"""

import torch
from torch.utils.data import TensorDataset, DataLoader
from transformers import GPT2Tokenizer, GPT2ForSequenceClassification
from sklearn.metrics import accuracy_score

# Data (tiny sample MiniProject Handout)
texts = [
    "The knight attacked the rook, Who the rook was attacked by was the knight .",
    "Who chased Tommy was that girl, That girl chased Tommy .",
    "A reporter stumped the coach, The coach was who a reporter stumped .",
    "The soldier was who the sergeant insulted, The sergeant was who the soldier insulted .",
    "Who the teacher mentioned was the Governor, The teacher was who was mentioned by the Governor !"
]

# Sentiment categories (0 = not a paraphrase pha, 1 = a paraphrase)
labels = [1, 1, 1, 0, 0]

# Other models:
# gpt
# gpt2-medium
# gpt2-large
# gpt2-xl

# Pick a model
gptmodel = "gpt2-medium"
# Pick a device
device = "cuda"

# Tokenize
tokenizer = GPT2Tokenizer.from_pretrained(gptmodel)

# GPT has no padding symbol for when the input exceeds the context window. This uses 'end of sequence' token for that purpose.
tokenizer.pad_token = tokenizer.eos_token

# max_length=128 is 128 tokens maximum per input (about 90–100 words)
enc = tokenizer(texts, truncation=True, padding=True, max_length=50, return_tensors="pt")

# Find longest example in terms of words, to be sure your window is appropriate
print('Longest sentence:', max([len(l.split()) for l in texts]))

# Each token gets a single numerical encoding (identifier, not its embedding)
print(enc["input_ids"])

# Not all positions in the context window contain a word that shold be involved in attention
print(enc["attention_mask"])

# Bundle the three tensors together, keeping them in sync by row
#   enc["input_ids"] = the tokenized text, each word/subword converted to an integer ID.
#   enc["attention_mask"] = 1 where there's a real token, 0 where it's padding.
#   torch.tensor(labels) = the correct answers, [0, 0, 0, 1, 1].
dataset = TensorDataset(enc["input_ids"], enc["attention_mask"], torch.tensor(labels))

attention_mask = enc["attention_mask"]
print(attention_mask)

input_ids = enc["input_ids"]
print(input_ids)

# Loader serves that data in batches, shuffled randomly each epoch.
loader  = DataLoader(dataset, batch_size=2, shuffle=True)

# Load GPT and specify number of output labels
model = GPT2ForSequenceClassification.from_pretrained(gptmodel, num_labels=2)

# Tokenizer.pad_token was set to tokenizer.eos_token, so must be model's pad token.
# Without it, GPT would complain because its default pad_token_id is None.
model.config.pad_token_id = tokenizer.eos_token_id

# Move model to GPU
model = model.to(device)

# Randomly split corpus into a training and a test subsets
from sklearn.model_selection import train_test_split

# Randomly split data set into a training data set (80%) and a test data set (20%)
Xtrain, Xtest, Ytrain, Ytest = train_test_split(texts, labels, test_size=0.2)

print(Xtrain)
print(Xtest)

print(Ytrain)
print(Ytest)

"""Encode the arrays as numbers that the model can understand instead of strings"""

# Vectorizer sentences
from sklearn.feature_extraction.text import TfidfVectorizer
import torch

#Covert the stings of test to a vectorized array of 1s and 0s with "fit_transform" used to handle spareness in the array

vectorizer = TfidfVectorizer()

Xtrain_tfidf = vectorizer.fit_transform(Xtrain).toarray()
Xtest_tfidf = vectorizer.transform(Xtest).toarray()

Xtrain = torch.tensor(Xtrain_tfidf)
Xtest = torch.tensor(Xtest_tfidf)

Ytrain = torch.tensor(Ytrain)

print(Xtrain)
print(Ytrain)

print(Xtest)
print(Ytest)

"""Train the GPT Model"""

from torch.utils.data import TensorDataset, DataLoader


# Batch size 32 (use a power of 2 to align with how GPU hardware works)
Atrain = attention_mask

# I got this error: RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.DoubleTensor instead (while checking arguments for embedding)
# so I used the ".long()" function on all the tensors since floating point numbers are not working and specifically asked for an int/long
dataset = TensorDataset(Xtrain.long(), Atrain.long(), Ytrain.long())
loader = DataLoader(dataset, batch_size=2, shuffle=True)


# Optimizer: Adam
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5)

# Set model for training
model.train()

# Making sure the tensor is actually there
print(attention_mask)
print(input_ids)
print(labels)


# Small number of epochs (2 to 4 is typical)
for epoch in range(1):
    for input_ids, attention_mask, labels in loader:
        input_ids, attention_mask, labels = input_ids.to(device), attention_mask.to(device), labels.to(device)
        loss = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels).loss
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
    print(f"Epoch {epoch+1} loss: {loss.item():.4f}")

from sklearn.metrics import accuracy_score

# Set model for evaluation
model.eval()

# Test set
test_texts  = ["Who fired Sam was Alex, Alex fired Sam", "Who hit Jimmy was Josh, Jimmy hit Josh", "Who loves Peter was Linda, Linda really loved Peter"]
test_labels = [1, 0, 1]

# Tokenize, encode, pad, etc. into Pytorch tensors (pt), and move to GPU
test_enc = tokenizer(test_texts, truncation=True, padding=True, max_length=50, return_tensors="pt").to(device)

# Run test data on fine-tuned model
with torch.no_grad():
    preds = model(**test_enc).logits.argmax(dim=-1).cpu().tolist()

# Print accuracy
print("Accuracy:", round(accuracy_score(test_labels, preds) * 100, 2), "%")